name: bloc_action_listener
description: Package adds a stream to which you can send actions from your Bloc or Cubit and process these actions on the UI similar to a BlocListener
version: 1.0.1
homepage: https://github.com/LanarsInc/bloc-action-listener

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  provider: ^6.0.5
  flutter_bloc: ^8.1.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2


flutter:
